# 公共配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
spring:
  application:
    name: springboot-init
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jybi_db
    username: root
    password: wjy
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 1
    host: 192.168.200.130
    port: 6379
    timeout: 5000
    password: wjy319214
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  #  elasticsearch:
  #    uris: http://localhost:9200
  #    username: root
  #    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB

  # rabbitmq
  rabbitmq:
    host: 192.168.200.130
    port: 5672
    username: admin
    password: 123
  # 以下是rabbitmq的可选配置
#    spring.rabbitmq.listener.type=simple
#    #设置为false，会丢弃消息或者重新发步到死信队列
#    spring.rabbitmq.listener.simple.default-requeue-rejected=false
#    #手动签收
#    spring.rabbitmq.listener.simple.acknowledge-mode=manual
#    #虚拟主机目录
#    spring.rabbitmq.virtual-host=/

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: false
    # 开启日志，输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx

# 鱼聪明AI 配置
yuapi:
  client:
    access-key: 1uiv3w2yr4e3ka0qwomv8j62bdslv8e6
    secret-key: p7gw3mvrn99mynq6yq971pxq8m7vhm01